guard :rspec, :cli => "--color --format doc" do
  watch(%r{^bin/(.+)$})
  watch(%r{^spec/.+_spec\.rb$})          { |m| "spec/codebreaker/game_spec.rb" }
  watch( 'lib/codebreaker/game.rb' )     { |m| "spec/codebreaker/game_spec.rb" }
end
