guard 'rspec',:cli => '--color --format doc', :all_after_pass => true, :all_on_start => true , :version => 2 do
  watch(%r{^bin/(.+)$})
  watch(%r{^spec/.+_spec\.rb$})          { |m| "spec/codebreaker" }
  watch(%r{^lib/codebreaker/.+\.rb$})          { |m| "spec/codebreaker" }
end

guard 'cucumber', :cli => '--color --format pretty' do
  watch(%r{^features/.+\.feature$})
  watch(%r{^features/step_definitions/.+\.rb$})
end
